#!/bin/bash

# Script para visualizar a estrutura do projeto Flutter

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  Gerenciador de Produtos com Flutter - Estrutura do Projeto   ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

tree -I 'build|.dart_tool' -L 3 -a

echo ""
echo "═════════════════════════════════════════════════════════════════"
echo ""
echo "📊 Resumo de Arquivos:"
echo ""
echo "📁 Configuração:"
echo "  • pubspec.yaml ..................... Dependências e metadados"
echo "  • .gitignore ....................... Arquivos ignorados no Git"
echo ""
echo "📁 Documentação:"
echo "  • README.md ........................ Guia principal de uso"
echo "  • STRUCTURE.md ..................... Estrutura detalhada"
echo "  • API_SETUP.md ..................... Configuração de APIs e estado"
echo "  • EXAMPLES.md ...................... Exemplos de integração"
echo ""
echo "📁 Código (lib/):"
echo "  • main.dart ........................ Ponto de entrada"
echo "  • models/product.dart ............. Modelo de dados"
echo "  • services/product_service.dart ... API CRUD"
echo "  • screens/ ......................... 3 telas de navegação"
echo "  • widgets/ ......................... 2 componentes reutilizáveis"
echo ""
echo "═════════════════════════════════════════════════════════════════"
echo ""
echo "🚀 Próximos Passos:"
echo ""
echo "1. Configure a URL da API em: lib/services/product_service.dart"
echo "   static const String baseUrl = 'https://sua-api.com/produtos';"
echo ""
echo "2. Instale as dependências:"
echo "   $ flutter pub get"
echo ""
echo "3. Execute a aplicação:"
echo "   $ flutter run"
echo ""
echo "4. Veja os exemplos em: API_SETUP.md e EXAMPLES.md"
echo ""
echo "═════════════════════════════════════════════════════════════════"
echo ""
echo "✨ Funcionalidades Implementadas:"
echo "  ✅ Listagem de produtos (GET)"
echo "  ✅ Criar novo produto (POST)"
echo "  ✅ Editar produto (PUT)"
echo "  ✅ Deletar produto (DELETE)"
echo "  ✅ Visualizar detalhes"
echo "  ✅ Validação de formulário"
echo "  ✅ Tratamento de erros"
echo "  ✅ Loading states"
echo "  ✅ Componentes reutilizáveis"
echo ""
echo "═════════════════════════════════════════════════════════════════"
